# config
logo: /images/logo.png
menu:
  首页: ' '
  文章: articles
  阅读: readings
  快记: cards
  标签: tags
  关于: about

# Content
excerpt_link: Read More

# Miscellaneous
rss: /atom.xml
google_analytics: false
